### ISSUE TITLE
cf-aws-tiny error: mapping values are not allowed in this context at line 69 column 9

### ISSUE THREAD

**Issue by elventear** [cloudfoundry-community/cf-boshworkspace#55]
I am trying to deploy using [terraform-aws-cf-install](https://github.com/cloudfoundry-community/terraform-aws-cf-install), the `cf-aws-tiny` template. 

During the provisioning step I see the following error:

```
> bosh deployment cf-aws-tiny
/home/ubuntu/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/psych.rb:370:in `parse': (<unknown>): mapping values are not allowed in this context at line 69 column 9 (Psych::SyntaxError)
        from /home/ubuntu/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'
        from /home/ubuntu/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/psych.rb:318:in `parse'
        from /home/ubuntu/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/psych.rb:245:in `load'
        from /home/ubuntu/.rvm/gems/ruby-2.1.6@cf-boshworkspace/gems/bosh-workspace-0.9.0.rc4/lib/bosh/workspace/helpers/project_deployment_helper.rb:18:in `project_deployment_file?'
        from /home/ubuntu/.rvm/gems/ruby-2.1.6@cf-boshworkspace/gems/bosh-workspace-0.9.0.rc4/lib/bosh/cli/commands/project_deployment.rb:18:in `set_current'
        from /home/ubuntu/.rvm/gems/ruby-2.1.6@cf-boshworkspace/gems/bosh_cli-1.2950.0/lib/cli/command_handler.rb:57:in `run'
        from /home/ubuntu/.rvm/gems/ruby-2.1.6@cf-boshworkspace/gems/bosh_cli-1.2950.0/lib/cli/runner.rb:56:in `run'
        from /home/ubuntu/.rvm/gems/ruby-2.1.6@cf-boshworkspace/gems/bosh_cli-1.2950.0/bin/bosh:16:in `<top (required)>'
        from /home/ubuntu/.rvm/gems/ruby-2.1.6@cf-boshworkspace/bin/bosh:23:in `load'
        from /home/ubuntu/.rvm/gems/ruby-2.1.6@cf-boshworkspace/bin/bosh:23:in `<main>'
        from /home/ubuntu/.rvm/gems/ruby-2.1.6@cf-boshworkspace/bin/ruby_executable_hooks:15:in `eval'
        from /home/ubuntu/.rvm/gems/ruby-2.1.6@cf-boshworkspace/bin/ruby_executable_hooks:15:in `<main>'
```
Which leads to a section that was introduced in https://github.com/cloudfoundry-community/cf-boshworkspace/commit/51019cc40049391c8e3a261202c1c6f19f118308:

````
  environment: cf-aws-tiny
    user: root      # Offending line
    server: false   # Offending line
```

If I remove those lines, then bosh will accept the manifest.

**Comment by elventear** [comment]
@longnguyen11288 any ideas on the cause of the problem?

**Comment by elventear** [comment]
NVM, my mistake.

**Comment by longnguyen11288** [comment]
sorry just saw this

**Comment by rkoster** [comment]
Looks like a yaml error (probably a missing `:`)
